---
# tasks file for apache
- name: instalamos paquetes
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ apache_packages }}"

- name: levantamos servicio
  service:
    name: "{{ apache_service }}"
    state: started
    enabled: yes
- name: crear pagina de bienvenida
  copy:
    src: index.html 
    dest: /var/www/html/index.html
  notify: "Restarted Service"
  