---
- hosts: "{{ servidores }}"
  become: true
  tasks:
  - name: copiamos template
    template:
      src: /tools/git_repositories/ansible_jsolanor/awx_labo_linux_jsolanor/template.j2
      dest: "/var/tmp/test2.conf"
      owner: root 
      group: root 
      mode: '0644'
  tasks:
  - name: copiamos fichero de config
    copy:
      src: /tools/git_repositories/ansible_jsolanor/awx_labo_linux_jsolanor/test.conf
      dest: "/var/tmp/test.conf"
      owner: root 
      group: root 
      mode: '0644'